-- --------------------------------------------------------
-- Host:                         192.168.2.12
-- Server version:               10.11.14-MariaDB-0ubuntu0.24.04.1 - Ubuntu 24.04
-- Server OS:                    debian-linux-gnu
-- HeidiSQL Version:             12.19.0.7314
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for dbold
CREATE DATABASE IF NOT EXISTS `dbold` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
USE `dbold`;

-- Dumping structure for table dbold.godggudang
CREATE TABLE IF NOT EXISTS `godggudang` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FGUDANG` varchar(3) NOT NULL,
  `FNAMA` varchar(30) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FGUDANG` (`FGUDANG`)
) ENGINE=MyISAM AUTO_INCREMENT=225 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- Dumping data for table dbold.godggudang: 114 rows
INSERT INTO `godggudang` (`ID`, `FGUDANG`, `FNAMA`) VALUES
	(111, 'GUD', 'Gudang Utama'),
	(112, 'GUD', 'IGD'),
	(113, 'GUD', 'Gudang Logistik'),
	(114, 'GUD', 'Poli Gigi'),
	(115, 'GO', 'GUDANG PERBEKALAN FARMASI'),
	(116, 'FAR', 'GUDANG FARMASI VINCENTIUS'),
	(117, 'P01', 'GUDANG PAVILIUN 1'),
	(118, 'P02', 'GUDANG PAVILIUN 2'),
	(119, 'P03', 'GUDANG PAVILIUN 3'),
	(120, 'P04', 'GUDANG PAVILIUN 4'),
	(121, 'P05', 'GUDANG PAVILIUN 5'),
	(122, 'P06', 'GUDANG PAVILIUN 6'),
	(123, 'P07', 'GUDANG PAVILIUN 7'),
	(124, 'P09', 'GUDANG PAVILIUN 9'),
	(125, 'P10', 'GUDANG PAVILIUN 10'),
	(126, 'P11', 'GUDANG PAVILIUN 11'),
	(127, 'P12', 'GUDANG PAVILIUN 12'),
	(128, 'ICU', 'GUDANG ICU'),
	(129, 'HD', 'GUDANG HD'),
	(130, 'UGD', 'GUDANG IGD'),
	(131, 'FIS', 'GUDANG FISIOTERAFI'),
	(132, 'RAD', 'GUDANG RADIOLOGI'),
	(133, 'KMB', 'GUDANG KAMAR BEDAH'),
	(134, 'LAB', 'GUDANG LABORATORIUM'),
	(135, 'RKM', 'GUDANG REKAM MEDIK'),
	(136, 'PLU', 'GUDANG POLIKLINIK 42 *'),
	(137, 'PLS', 'GUDANG GSY FARMASI'),
	(138, 'TPA', 'TEMPAT PENITIPAN ANAK'),
	(139, 'KMK', 'GUDANG KAMAR MAKAN'),
	(140, 'BPA', 'BIARA PROPINSI ALAT'),
	(141, 'ECG', 'GUDANG ECG'),
	(142, 'SS', 'GUDANG SENTRAL STERILISASI'),
	(143, 'P08', 'GUDANG PAVILIUN 8'),
	(144, 'SE', 'GUDANG SEKRETARIS'),
	(145, 'KTS', 'KAMAR TAMU SUSTERAN'),
	(146, 'UKS', 'GUDANG USAHA KESEHATAN SEKOLAH'),
	(147, 'PEN', 'GUDANG PENDIDIKAN'),
	(148, 'TEK', 'GUDANG TEKNISI'),
	(149, 'EEG', 'GUDANG LAB  EEG'),
	(150, 'LL', 'GUDANG LAIN-LAIN'),
	(151, 'GRT', 'GUDANG RUMAH TANGGA'),
	(152, 'KT', 'GUDANG KAMAR TERIMA'),
	(153, 'PST', 'GUDANG POSTULAN'),
	(154, 'KMC', 'GUDANG LAUNDRY'),
	(155, 'KBA', 'GUDANG KB ALAMIAH'),
	(156, 'UDC', 'UNIT DAY CARE'),
	(157, 'KM', 'KOMITE MEDIK'),
	(158, 'EXP', 'PEMUSNAHAN OBAT EXP.DATE'),
	(159, 'PC', 'GUDANG PASTORAL CARE'),
	(160, 'EMA', 'GUDANG ASRAMA EMAUS'),
	(161, 'SUS', 'GUDANG SUSTERAN'),
	(162, 'PHC', 'GUDANG PUBLIC HEARTH CARE'),
	(163, 'STP', 'SATPAM'),
	(164, 'ADM', 'ADMINISTRASI'),
	(165, 'UPL', 'UNIT PENJUALAN LAIN'),
	(166, 'NCU', 'GUDANG NEONATUS ICU'),
	(167, 'P15', 'GUDANG PAVILIUN 15'),
	(168, 'P14', 'GUDANG PAVILIUN 14'),
	(169, 'LOG', 'GUDANG LOGISTIK UMUM'),
	(170, 'GZ', 'GUDANG GIZI'),
	(171, 'P49', 'POLI DIPONEGORO 49 *'),
	(172, 'IC1', 'ICU - 1'),
	(173, 'IC2', 'ICU - 2-3'),
	(174, 'IC4', 'ICU - 4'),
	(175, 'PLJ', 'POLI JAGIR'),
	(176, 'PLK', 'POLI KARAH'),
	(177, 'UP1', 'UPL/RSK. MARGI RAHAYU, BATU'),
	(178, 'UP2', 'UPL/RSK. PANTISILA, SINGARAJA'),
	(179, 'UP3', 'UPL/RSK. BUDI RAHAYU, BLITAR'),
	(180, 'UP4', 'UPL/RSK.ST ANTONIUS, LOMBOK'),
	(181, 'GM', 'GUDANG MEDIS'),
	(182, 'KP', 'GUDANG KANTOR PERAWATAN'),
	(183, 'P18', 'GUDANG POLI JANTUNG *'),
	(184, 'P32', 'GUDANG POLI 32 -ANAK *'),
	(185, 'AKP', 'GUDANG POLI AKUPUNTUR'),
	(186, 'UP', 'GUDANG UNIT PRODUKSI'),
	(187, 'EDP', 'GUDANG EDP'),
	(188, 'PU', 'GUDANG PU'),
	(189, 'DIK', 'GUDANG DIKLAT KEPERAWATAN'),
	(190, 'IPS', 'GUDANG IPS'),
	(191, 'SSK', 'GUDANG SUSTERAN SAKIT'),
	(192, 'ASK', 'GUDANG DEPO ASKES'),
	(193, 'RSK', 'RUSAK TDK BS RETUR PBF'),
	(194, 'SDM', 'GUDANG PERSONALIA'),
	(195, 'DAP', 'GUDANG DAPUR'),
	(196, 'GA', 'GUDANG GRIYA ARNOLDUS'),
	(197, 'PKL', 'GUDANG PEMELIHARAAN KES. LINGK'),
	(198, 'WQA', ''),
	(199, 'PLG', 'GUDANG POLI GIGI 36'),
	(200, 'POS', 'PENCAMPURAN OBAT STERIL'),
	(201, 'P39', 'GUDANG POLI MATA 39'),
	(202, 'FK', 'FARMASI KLINIS'),
	(203, 'HCU', 'GUDANG HIGH CARE UNIT'),
	(204, 'PDS', 'PONDOK SEHAT'),
	(205, 'P51', 'GUDANG KLINIK SORE 51'),
	(206, 'P47', 'GUDANG KLINIK INOVASI'),
	(207, 'AGT', 'GUDANG PAV. AGUSTINUS'),
	(208, 'J20', 'GUDANG KLINIK JAMBI 20'),
	(209, 'POK', 'PENCAMPURAN OBAT KEMO'),
	(210, 'SKD', 'SEKRETARIS DIREKTUR'),
	(211, 'SY1', 'GUDANG GSY LANTAI 1'),
	(212, 'SY2', 'GUDANG GSY LANTAI 2'),
	(213, 'SY3', 'GUDANG GSY LANTAI 3'),
	(214, 'KIA', 'GUDANG KIA'),
	(215, 'SY6', 'GUDANG GSY LANTAI 6'),
	(216, 'SY7', 'GUDANG GSY LANTAI 7'),
	(217, 'OKY', 'KAMAR BEDAH MATERNITAS'),
	(218, 'ELI', 'GUDANG ELISABET'),
	(219, 'GTR', 'TRANSPORTASI'),
	(220, 'VAC', 'GUDANG VAKSIN COVID'),
	(221, 'KTM', 'ADMISSION & CUSTOMER CARE/KTM'),
	(222, 'CTH', 'GUDANG CATHETERISASI'),
	(223, 'DAM', 'GUDANG DAMIAN'),
	(224, 'GPT', 'GUDANG PERTUKANGAN');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
