CREATE TABLE `sp_pesanan` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`iddbf` INT(11) NOT NULL DEFAULT '0',
	`no_sp` VARCHAR(15) NOT NULL COLLATE 'latin1_swedish_ci',
	`tgl_sp` DATE NOT NULL DEFAULT '1900-01-01',
	`namasup` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`kodesup` VARCHAR(6) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`no_tawar` VARCHAR(25) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`tgl_tawar` DATE NOT NULL DEFAULT '1900-01-01',
	`barang` VARCHAR(90) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`model` VARCHAR(35) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`merk` VARCHAR(35) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`spec` VARCHAR(55) NOT NULL DEFAULT '' COLLATE 'latin1_swedish_ci',
	`qty` DOUBLE(12,2) NOT NULL DEFAULT '0.00',
	`satuan` VARCHAR(10) NOT NULL COLLATE 'latin1_swedish_ci',
	`total` DOUBLE(16,2) NOT NULL DEFAULT '0.00',
	`harga` DOUBLE(16,2) NOT NULL DEFAULT '0.00',
	`pembayaran` VARCHAR(60) NOT NULL COLLATE 'latin1_swedish_ci',
	`pembayaran1` VARCHAR(60) NOT NULL COLLATE 'latin1_swedish_ci',
	`notein` VARCHAR(100) NOT NULL COLLATE 'latin1_swedish_ci',
	`noteout1` VARCHAR(100) NOT NULL COLLATE 'latin1_swedish_ci',
	`noteout` VARCHAR(100) NOT NULL COLLATE 'latin1_swedish_ci',
	`noteout2` VARCHAR(100) NOT NULL COLLATE 'latin1_swedish_ci',
	`user` VARCHAR(20) NOT NULL COLLATE 'latin1_swedish_ci',
	`flag` DOUBLE(16,2) NOT NULL DEFAULT '0.00',
	`uang` VARCHAR(10) NOT NULL COLLATE 'latin1_swedish_ci',
	`xx` VARCHAR(1) NOT NULL COLLATE 'latin1_swedish_ci',
	`tglkirim` DATE NOT NULL DEFAULT '1900-01-01',
	`ppn` DOUBLE(16,2) NOT NULL DEFAULT '0.00',
	`potongan` DOUBLE(16,2) NOT NULL DEFAULT '0.00',
	`unit` VARCHAR(20) NOT NULL DEFAULT '0' COLLATE 'latin1_swedish_ci',
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `no_sp` (`no_sp`) USING BTREE,
	INDEX `tgl_sp` (`tgl_sp`) USING BTREE,
	INDEX `kodesup` (`kodesup`) USING BTREE,
	INDEX `barang` (`barang`) USING BTREE,
	INDEX `model` (`model`) USING BTREE,
	INDEX `unit` (`unit`) USING BTREE,
	INDEX `iddbf` (`iddbf`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=MyISAM
AUTO_INCREMENT=1027
;