CREATE TABLE `m_supplier` (
	`IdSupplier` INT(11) NOT NULL AUTO_INCREMENT,
	`KodeSupplier` VARCHAR(6) NOT NULL COLLATE 'latin1_swedish_ci',
	`NamaSupplier` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`NPWP` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Alamat1` VARCHAR(100) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Alamat2` VARCHAR(100) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Kota2` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Telp1` VARCHAR(20) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Telp2` VARCHAR(20) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Telp3` VARCHAR(20) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Kota1` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`ContactPerson` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Mobile1` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Mobile2` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Fax1` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Fax2` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Email1` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Email2` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Status` VARCHAR(20) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`KontrakAwal` DATE NULL DEFAULT NULL,
	`KontrakAkhir` DATE NULL DEFAULT NULL,
	`CaraPembayaran` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`NamaBank` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`NoRekening` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`TempoPembayaran` VARCHAR(20) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`JamPengiriman` VARCHAR(30) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`KodePerkiraan` CHAR(4) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`Keterangan1` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`ffarmasi` CHAR(1) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`UserCreated` CHAR(5) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`DateTimeCreated` DATETIME NULL DEFAULT NULL,
	`Flag` CHAR(1) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`KodePerkiraanBaru` CHAR(5) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`tanda` VARCHAR(1) NOT NULL COMMENT 'P=proyek I=implan' COLLATE 'latin1_swedish_ci',
	`NamaInvoice` VARCHAR(100) NOT NULL COLLATE 'latin1_swedish_ci',
	PRIMARY KEY (`IdSupplier`, `KodeSupplier`) USING BTREE,
	INDEX `ndx1` (`NamaSupplier`) USING BTREE,
	INDEX `indexmsupplier` (`KodeSupplier`, `NamaSupplier`) USING BTREE,
	INDEX `namasupplierflag` (`NamaSupplier`, `Flag`) USING BTREE,
	INDEX `Status` (`Status`) USING BTREE,
	INDEX `tanda` (`tanda`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=MyISAM
AUTO_INCREMENT=2448
;