CREATE TABLE m_supplier (
    IdSupplier INT PRIMARY KEY,
    KodeSupplier VARCHAR(6),
    NamaSupplier VARCHAR(30),
    NPWP VARCHAR(30),
    Alamat1 VARCHAR(100),
    Alamat2 VARCHAR(100),
    Kota2 VARCHAR(30),
    Telp1 VARCHAR(20),
    Telp2 VARCHAR(20),
    Telp3 VARCHAR(20),
    Kota1 VARCHAR(30),
    ContactPerson VARCHAR(30),
    Mobile1 VARCHAR(30),
    Mobile2 VARCHAR(30),
    Fax1 VARCHAR(30),
    Fax2 VARCHAR(30),
    Email1 VARCHAR(50),
    Email2 VARCHAR(50),
    Status VARCHAR(20),
    KontrakAwal DATE,
    KontrakAkhir DATE,
    CaraPembayaran VARCHAR(30),
    NamaBank VARCHAR(30),
    NoRekening VARCHAR(50),
    TempoPembayaran VARCHAR(20),
    JamPengiriman VARCHAR(30),
    KodePerkiraan CHAR(4),
    Keterangan1 VARCHAR(50),
    ffarmasi CHAR(1),
    UserCreated CHAR(5),
    DateTimeCreated DATETIME,
    Flag CHAR(1),
    KodePerkiraanBaru CHAR(5),
    tanda VARCHAR(1),
    NamaInvoice VARCHAR(100)
);
CREATE TABLE dap_sp_h (
    id INT PRIMARY KEY,
    tgl_pesan DATE,
    tgl_kirim DATE,
    gudang VARCHAR(3),
    jenis_bayar VARCHAR(6),
    supplier VARCHAR(6),
    acc1 VARCHAR(20),
    acc2 VARCHAR(20),
    keterangan TEXT,
    flag VARCHAR(1),
    user VARCHAR(10),
    dtime_created DATETIME
);
CREATE TABLE dap_sp_d (
    id INT PRIMARY KEY,
    id_sp INT,
    id_barang INT,
    id_kategori INT,
    id_satuan INT,
    id_merek INT,
    id_kelompok INT,
    jumlah DECIMAL(9, 2),
    terima DECIMAL(9, 2),
    harga DECIMAL(9, 2),
    disc DECIMAL(9, 2)
);
CREATE TABLE sp_pesanan (
    id INT PRIMARY KEY,
    iddbf INT,
    no_sp VARCHAR(15),
    tgl_sp DATE,
    namasup VARCHAR(50),
    kodesup VARCHAR(6),
    no_tawar VARCHAR(25),
    tgl_tawar DATE,
    barang VARCHAR(90),
    model VARCHAR(35),
    merk VARCHAR(35),
    spec VARCHAR(55),
    qty DOUBLE,
    satuan VARCHAR(10),
    total DOUBLE,
    harga DOUBLE,
    pembayaran VARCHAR(60),
    pembayaran1 VARCHAR(60),
    notein VARCHAR(100),
    noteout1 VARCHAR(100),
    noteout VARCHAR(100),
    noteout2 VARCHAR(100),
    user VARCHAR(20),
    flag DOUBLE,
    uang VARCHAR(10),
    xx VARCHAR(1),
    tglkirim DATE,
    ppn DOUBLE,
    potongan DOUBLE,
    unit VARCHAR(20)
);
ALTER TABLE dap_sp_h
ADD FOREIGN KEY (supplier) REFERENCES m_supplier (KodeSupplier);
ALTER TABLE sp_pesanan
ADD FOREIGN KEY (kodesup) REFERENCES m_supplier (KodeSupplier);
ALTER TABLE dap_sp_d
ADD FOREIGN KEY (id_sp) REFERENCES dap_sp_h (id);